[workspace]
members = [
  "canister_a",
  "canister_b",
]
resolver = "2"

[workspace.package]
license = "MIT"
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
candid = { version = "0.10" }
flate2 = "1"
futures = { version = "0.3", default-features = false }
ic-cdk = "0.12"
log = "0.4"
once_cell = "1"
pocket-ic = "2.1"
reqwest = { version = "0.11", default-features = false }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.37"
tokio = { version = "1", features = ["rt", "macros"] }

[profile.release]
# wasm32 defaults to `panic=abort`. As it is the only supported mode, setting it manually to `unwind` has no effect for wasm32 builds
panic = "unwind"
debug = false